version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ms_sdr_backend
    ports:
      - "${PORT:-8080}:8080"
    env_file:
      - .env
    environment:
      - GIN_MODE=${GIN_MODE:-release}
    restart: unless-stopped
